//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeWorld
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventaireHero
    {
        public int IdHero { get; set; }
        public int ItemId { get; set; }
        public int IdInventaireHero { get; set; }
    
        public virtual Hero Hero { get; set; }
        public virtual Item Item { get; set; }
    }
}
